### ISSUE TITLE
Merge send & update in effects

### ISSUE THREAD

**Issue by cassiozen** [cassiozen/useStateMachine#28]
Effects provided two functions as parameters: `send` & `update`. 
In many cases (as illustrated by the[ async example](https://github.com/cassiozen/useStateMachine/blob/e26c24a2717737682622d47672c3fec76ea60a2b/examples/fetch/index.tsx#L37)), `send` & `update` will be used together. 
Maybe instead of two separate functions, we should have an overloaded 'send':

```typescript
send(event: string)
send(event: string, updater: fn)
send(updater:fn)
```

**Comment by dani-mp** [comment]
Could the effect get the current state/context already as a param? Then we wouldn't need an updater function, and the send fn can be just `send(event: string, context: any)`, with the second argument being optional if you want to keep the previous context.

I would go further and create an API that makes it impossible to `send` more than once within the same effect, to avoid race conditions. Now, you can transition to a different machine state several times within the same effect, and also update the context several times. Both things seem counterintuitive. For instance, what happens if I `send` and then `update`?

**Comment by cassiozen** [comment]
The updater function is useful because you might want to update something based on the current context, like incrementing a counter for example.

**Comment by RichieAHB** [comment]
If you pass a `getContext()` thunk as the final parameter for the `effect`, then this could probably solve your the issue with https://github.com/cassiozen/useStateMachine/issues/33#issuecomment-850026571 and also remove the need for the `updater` function (which I assume is also provided to avoid stale access to context)?

**Comment by dani-mp** [comment]
@cassiozen yeah, that's why I mentioned that the effect function should get the context as a param, or as @RichieAHB mentioned, a function to get the context.

I think if an effect can update the context only once—as suggested in my second paragraph above—, and transition only once, then I don't think how we can end up with a stale context, given that the state machine transitions are synchronous.

**Comment by cassiozen** [comment]
Please check proposal in #35
