### ISSUE TITLE
Question about useConstant

### ISSUE THREAD

**Issue by burtek** [cassiozen/useStateMachine#55]
https://github.com/cassiozen/useStateMachine/blob/85d373eeb6c30e1e17c2fc58711ede605f830a0b/src/index.tsx#L197-L204

https://github.com/cassiozen/useStateMachine/blob/85d373eeb6c30e1e17c2fc58711ede605f830a0b/src/index.tsx#L218-L220

How is `useConstant` here better/different from `react`'s `useMemo`? It looks like it should work same as

```ts
const reducer = useMemo(() => getReducer<Context, Events, State, EventString>(config), []);
```

**Comment by devanshj** [comment]
Because `useMemo` doesn't guarantee that the function would be run only once, [from the docs](https://reactjs.org/docs/hooks-faq.html#how-to-create-expensive-objects-lazily)...
> useMemo lets you memoize an expensive calculation if the dependencies are the same. However, it only serves as a hint, and doesn’t guarantee the computation won’t re-run. But sometimes you need to be sure an object is only created once.

Perhaps you'd be interested in comparison with other ways to do this and similar discussion in the issue pages of [useConstant's repo](https://github.com/Andarist/use-constant)

**Comment by burtek** [comment]
that makes sense, thank you :)
