### ISSUE TITLE
How to use external machine config with correct type (using TypeScript)?

### ISSUE THREAD

**Issue by fabiradi** [cassiozen/useStateMachine#78]
First of all, thanks for this great little library built for React! The machine syntax is really nice and also the **TypeScript support**. 👍

My problem is that I want to **first define the machine config** and then **use the config object for the hook**. Using [your sample machine](https://github.com/cassiozen/useStateMachine#sample-usage), it would look like this:

```javascript
const machine = {
  initial: 'inactive',
  states: {
    inactive: {
      on: { TOGGLE: 'active' },
    },
    active: {
      on: { TOGGLE: 'inactive' },
      effect() {
        console.log('Just entered the Active state');
        // Same cleanup pattern as `useEffect`:
        // If you return a function, it will run when exiting the state.
        return () => console.log('Just Left the Active state');
      },
    },
  },
}

const [state, send] = useStateMachine(machine)
```

The error that I get is:

```
Argument of type '{ initial: string; states: { inactive: { on: { TOGGLE: string; }; }; active: { on: { TOGGLE: string; }; effect(): () => void; }; }; }' is not assignable to parameter of type 'InferNarrowestObject<Definition<{ initial: string; states: { inactive: { on: { TOGGLE: string; }; }; active: { on: { TOGGLE: string; }; effect(): () => void; }; }; }, { inactive: { on: { TOGGLE: string; }; }; active: { on: { TOGGLE: string; }; effect(): () => void; }; }, undefined, false>>'.
  Types of property 'initial' are incompatible.
    Type 'string' is not assignable to type '"inactive" | "active"'.ts(2345)
```

I tries the following types without any success:

```javascript
const machine1: Machine.Definition.Impl = { /* */ }
const machine2: Machine.Definition<unknown, { inactive: 'inactive'; active: 'active' }> = { /* */ }
```

I also tried to _get around the error_ by definition my own type. But it is incomplete and I don't want to redefine something that already exists somewhere else.

```javascript
  interface IMachine {
    initial: string
    states: {
      [key: string]: {
        on: { [key: string]: string | { target: string /*guard?: any*/ } }
        effect?: () => void // works, but misses the arguments...
      }
    }  
  }

```

🤷🏻 How do I solve this problem in a clean way with defining my own types? They are already there. I just cannot figure how to apply them correctly.

**Comment by devanshj** [comment]
This is a limitation and not a limitation (I'll explain why in a bit) but the workaround is to make the machine definition a "unit type" aka "literal" with `as const` like [this][1]

I say "not a limitation" because you should almost never define the definition in a variable, for the various reason:
1. Errors would be less readable, like [here][2], scroll all the way down in the tooltip to see `"foo"` is not assignable to `"inactive" | "active"`
2. You get no completions/suggestions when you write your defintion
3. You'll have to type the effect & guard parameters yourself, they can't be inferred because we leverage contextual inference to compute them precisely. For example:

```ts

useStateMachine({
  initial: "a",
  states: {
    a: {
      on: { X: "b" }
    },
    b: {
      effect: ({ event }) => {
        event.type; // event.type "X"
      }
    }
  }
})

useStateMachine({
  initial: "b", // <-- change here
  states: {
    a: {
      on: { X: "b" }
    },
    b: {
      effect: ({ event }) => {
        event.type; // event.type is "$$initial" | "X"
      }
    }
  }
})
```

So the definition creates it's type from itself! 

https://github.com/cassiozen/useStateMachine/blob/6b0ac5306ebc26d310933c38d097f88ae7ab192b/src/types.ts#L5

As you can see it says `D extend Machine.Defintion<D>` so the constraint of `D` is a derivative of itself! So you can't assign to a variable and get the same experience, because the definition needs to be a generic. Oh wait, you can do it with an identity function haha because there you can make it a generic, wait let show you.
```ts
import useStateMachine from "@cassiozen/usestatemachine";
import { Machine, A } from "@cassiozen/usestatemachine/dist/types";

const createDefinition =
  <D extends Machine.Definition<D>>(definition: A.InferNarrowestObject<D>) =>
    definition

const machine = createDefinition({
  initial: 'inactive',
  states: {
    inactive: {
      on: { TOGGLE: 'active' },
    },
    active: {
      on: { TOGGLE: 'inactive' },
      effect() {
        console.log('Just entered the Active state');
        // Same cleanup pattern as `useEffect`:
        // If you return a function, it will run when exiting the state.
        return () => console.log('Just Left the Active state');
      },
    },
  },
})

const [state, send] = useStateMachine(machine)
```

[There][3] you problem is solved! And this will you the exact same experience as if you were directly writing it in `useStateMachine` (because the types are the same).

So I take back the `as const` advice a better way to do this, I think we'll export a `createDefinition` in the next release (subject to Cassio's agreement), but I'll personally still suggest you to write it directly in `useStateMachine` but it's okay even if you use `createDefinition`, it's a matter of taste I guess.

Oh wait I think you want to write in a variable so that you can write the machine outside the component as to separate behavior from view, oh that makes sense haha in that case even I might write using `createDefinition` -- so I also take back the writing directly in `useStateMachine` suggestion xD -- in that case `createDefinition` becomes even more important feature.

Thanks for your feedback! And also glad that you're liking the TypeScript support! (coz it's me who wrote the types :P)

I think we'll keep this issue open till we release a version with `createDefinition`. I actually [already had in my mind](https://github.com/cassiozen/useStateMachine/pull/36#issuecomment-886940645) just forgot haha.

[1]: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAVwM4FMDKMCGMUFlMDGAFsAHYpwBmUEIcARAAIGZJLAQBeKpA9MiiRYcIQiXL0A3AChpBCKSFxRxMhQC8cAN7S4cMsBjBMAGwBccAORlCRgG4pLAGl1wh2QRZ169NgvZQvVx84BS84ABUAeQBxGIAZAFELS1tgB0s4AF8XEJzguDSHIJC9MO1I2ITkqz8AzPzSuBRKShR-AAoASm0CkPlFCBMUADoTCABzDssAKWR4HhwoFAATOBgiCgBBf3SKdxxLLpkmvV5eODRMEAoCYcxSBDA4MGwl0kKkOAADAUTW9owb5mPo+c5wACSlDgAE8IAg4MsYAgoB9MFQEKRdgonPp4AB3YAmEyIzFwfGbD4oAAehjIE3WmzcwlGoL0SJRH26cHUAD44AMkENRuMprN5nB4i14BttrsHMyPEcTqVGj41fksp8BQohLJBfAANoHFC41CkFYAXR5iFQGA8+FU5A6KnEKC6QA

[2]: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAVwM4FMDKMCGMUFlMDGAFsAHYpwBmUEIcARAAIGZJLAQBeKpA9MiiRYcIQiXL0A3AChpBCKSFxRxMhQC8cAN7S4cMsBjBMAGwBccAORlCRgG4pLAGl1wh2QRZ169NgvZQvVx84BS84ABUAeQBxGIAZAFELS0oICEs4AF8XEJzguFtgByCQvTDtSNiE5Ks-AMz8srgUSkoUfwAKAEptApD5RQgTFAA6EwgAc07LAClkeB4cKBQAEzgYIgoAQX9iinccS26ZZr1eXjg0TBAKAhHMUgQwODBsZdJCpDgAAwFEtodGA-Mz9HwXOAASUocAAnhAEHAVjAEFBPpgqAhSHsFE59PAAO7AEwmJFYuAErafFAAD0MZEmGy2bmEYzBemRqM+PTg6gAfHBBkhhmMJtM5gs4PFWvBNjs9g4WR5jqcyk0fOr8lkvoKFEJZEL4ABtQ4oPGoUirAC6vMQqAwHnwqnInRU4hQ3SAA

[3]: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAVwM4FMDKMCGMUFlMDGAFsAHYpwBmUEIcARAAIGZJLAQBeKpA9MiiRYcIQiXL0A3AChQkWHADecfMTIoANHACCcAL5UadJizYdufAUOwpRa8rwAmwIbxgBPMIKnTpBCKRCcARQKDYAIiiUZMAwHKRwALzScHAAPOFwKAAeOKSOSCpi6gB0kdGksfEZAHw1ABSOUTFxAQBcOiUAkqSUKFAAcphQNADugjAA8gBGAFYoBDC1AJRJNSmpcE0VVQG+-oHwduIUicGhEc2VraT1ihstwJgANh0A5GSEcQBuKG8aG2sOCQHXumzgn0WwF+oI24PaSjgABVJgBxVEAGQAou8vtC-voAeC9ETNniYUo4ZsEcoUejse9IT8CSSqakon1FvVVmDwZsDkgIM8UCVnhAAOb1N4AKWQ8B4OFCjjgMCIFG0UN+cCBf2WMj5m14vDgaEwIAoBGFmFICDAcDA2EVCVYcAABgIsZROTBXW02YbjV1KHB3BAEHBQjAEFBnVQEKQoQEtLE4KNgM9nhH46m1QkclVSOKVWrtcIRf7UpHowluWtggFBcLRRKpbKghiovBVerNRQdW89f7WcTSay9Mt9g34ABtHVaVD5AC6SUQqAwNlUJ3qx3UE6AA

**Comment by fabiradi** [comment]
Thank you so much for taking the time to compile this detailed answer 👍🏻 . It explains the context very well and I can see a lot of similarities to xstate. It took me some time to try it again.

I had a lot of hope that I could, now, get it to work. However, there is a problem with `effect()` that keeps me thinking. Auto-completion works well and the same  "machine" also **works without a problem in JS/ES6**. As soon as the same is ported to TypeScript, it throws errors.

I'm sticking to the example from your readme to not include any mistakes that I might make without knowing.

```javascript
import { Meta, Story } from '@storybook/react'
import useStateMachine, { t } from '@cassiozen/usestatemachine'
import { Machine, A } from '@cassiozen/usestatemachine/dist/types'

export default {
  title: 'Spike/Machine',
} as Meta

const createDefinition = <D extends Machine.Definition<D>>(definition: A.InferNarrowestObject<D>) => definition

const machine = createDefinition({
  initial: 'inactive',
  schema: {
    context: t<{ toggleCount: number }>(),
  },
  context: { toggleCount: 0 },
  states: {
    inactive: {
      on: { TOGGLE: 'active' },
    },
    active: {
      on: { TOGGLE: 'inactive' },
      effect({ event, context, setContext }) { // 🚧 Adding arguments here causes the errors at useMachine(...)
        console.log('Just entered the Active state', { context })
        // Same cleanup pattern as `useEffect`:
        // If you return a function, it will run when exiting the state.
        return () => console.log('Just Left the Active state')
      },
    },
  },
})

export const Overview: Story = () => {
  const [state, send] = useStateMachine(machine) // ⛔️ <-- The error arises here (see below for error message)

  return (
    <>
      <h3>Machine</h3>
      <div>
        {state.nextEvents.map(item => (
          <button key={item} onClick={() => send(item)}>
            {item}
          </button>
        ))}
      </div>
      <pre>{JSON.stringify(state, null, 2)}</pre>
    </>
  )
}
```

The error text:

```
Argument of type 'InferNarrowestObject<Definition<{ initial: "inactive"; schema: { context: { [$$t]: { toggleCount: number; }; }; }; context: { toggleCount: number; }; states: { inactive: { on: { TOGGLE: "active"; }; }; active: { on: { TOGGLE: "inactive"; }; effect: unknown; }; }; }, { ...; }, { ...; }, true>>' is not assignable to parameter of type 'InferNarrowestObject<Definition<Definition<{ initial: "inactive"; schema: { context: { [$$t]: { toggleCount: number; }; }; }; context: { toggleCount: number; }; states: { inactive: { on: { TOGGLE: "active"; }; }; active: { on: { TOGGLE: "inactive"; }; effect: unknown; }; }; }, { ...; }, { ...; }, true>, { ...; }, un...'.
  The types of 'states.inactive.effect' are incompatible between these types.
    Type 'Effect<{ initial: "inactive"; schema: { context: { [$$t]: { toggleCount: number; }; }; }; context: { toggleCount: number; }; states: { inactive: { on: { TOGGLE: "active"; }; }; active: { on: { TOGGLE: "inactive"; }; effect: unknown; }; }; }, [...], "inactive"> | undefined' is not assignable to type 'Effect<Definition<{ initial: "inactive"; schema: { context: { [$$t]: { toggleCount: number; }; }; }; context: { toggleCount: number; }; states: { inactive: { on: { TOGGLE: "active"; }; }; active: { on: { TOGGLE: "inactive"; }; effect: unknown; }; }; }, { ...; }, { ...; }, true>, [...], "inactive"> | undefined'.ts(2345)
```

### Nest steps?

* What am I doing wrong? The _same_ definition works without a problem when used **directly** in `useMachine`.

>  How can I use the great machine syntax? I really like the way, machines can be defined!

### Why all that?

* The main reason for me is to "just" get the **machine definition** and create a **mermaid chart** out of it.
* Another solution might be to also **export the machine definition** from `useMachine()`? This might be even simpler...

```javascript
const [state, send, definition] = useStateMachine(machine)
```

---

```mermaid
graph TD
    start( ) --> inactive
    inactive --TOGGLE--> active
    active --TOGGLE--> inactive
```

<img width="163" alt="statemachine-mermaid" src="https://user-images.githubusercontent.com/5428213/131755203-39da7fd7-3f72-4c47-8bae-361641f1d259.png">

**Comment by devanshj** [comment]
Thanks for reporting you're providing really useful feedback!

It's a known typescript limitation (I forgot about this) that `effect`s become `unknown` (when using parameters) after you pass the definition to `createDefinition`. One workaround is to replace `effect: unknown` with `effect: any` you can use this updated `createDefinition`

```ts
import { Machine, A } from '@cassiozen/usestatemachine/dist/types'

const createDefinition = <D extends Machine.Definition<D>>(definition: A.InferNarrowestObject<D>) =>
  definition as MapEffectsToAny<D extends Machine.Definition<infer X> ? X : never>

type MapEffectsToAny<T> =
  T extends object
    ? { [K in keyof T]: K extends "effect" ? any : MapEffectsToAny<T[K]> }
    : T
```

[Now your snippet compiles][1]. Once we publish a version with `createDefinition` it's going to be easy to write definitions outside.

[1]: https://www.typescriptlang.org/play?jsx=1&ts=4.3.5#code/JYWwDg9gTgLgBAbzgWQKYwIYBo4GUbQCecAvnAGZQQhwDkAAgM4FSEBGEEA1gPRSoYAxjFoAoUJFhwAro1T4MMVMiEALYADtUOJPDKVqdeoIyNGwCAC9UGnrNTNFqEGs2oxE6PCQrB6rTgAgqQUVDQMJmYW1rb2jkoufm48ACbAzDwwhGAOYqKoAB6S8Cmo5BjSADbeonBwMMAwlagAXHS4YMBcqDy+-u5YomSmKOgYoqKCEBrMcIL8TgAiZZqNFhpwALxwADyLcIVKGimMKK5aAHTL5KsN03sAfA8AFKU3GmvTbYEXAJIa5FQUAAchgoFQAO4OGAAeTYACtUMJHgBKLYPWpwN63dZwEYqMAAUXIgOEjAAKhBAhpCHsDgUjiczklLtccfdNICoHAABoPOAAfl5cDaWgAbkCMaIsjkzkSSUiYBSqTSduT+ZtMeT6YzThAEYrMXUhUgANoAaTgmjg3UIEHIcHJAF02pbDjYmQAiMqkmCewV4mkiuXE33K6m08kWp38khG4PkiZTGbwRL9LZzBZKNkfO4aZ4ITE4jCVNq0TRCBoS2iDOqMPzODBtQt1OrJpQMtowHa6CAAcz7zQAwhBpBoYKLpCA2EDSC8UbXSIv24dm-V+4PUCOxxO4AAGJeY+IOZvxivCYAS0+t1tfRCOmEAcUfABlCWXK5f3IebyRF3VPyvRB4zqO8kHJJ9X3fOhzyrb8-xAg4FWEAsDglcccBXBkcDkGAR3HQ5SDRFsb1bZNGAgZoLkqftnloAApWR4BsJR+BSepVFQOBAgvCU4GPGt7ywvQUUQuoeB4PAMBALjBGaDANGkMA4DARRWI2EYAAN7FDRVNJaMS4AkuBfgdO1pDgfgYGkKANIoMcL2mHBGjgCFgEqSpLLHVzOI2Qo1g0PsOK448LkMqybI2Z40U2flyMo1BqNohimLgF8yngGBOO43iQswJRaFE0if1bBC6gQkhRPyIovDmaZZhhCUoDFYBUAhNp8CIDNovRYC23q+BTWPHCPSdDN7AUJQ+jcZ40zcKq6gi2y4GeeMdgxYqdlUABmB5pq0HYeB2jbSJ2NIxRO4qEFCrQGUJdClQuFwwGeRpnF61bipvHY2GkGACA2W1NgQN6QDIaYh0qYBBC4YGeti-iPVehIURIS6vrqEGEjjDG6kO37-umdGbxRVHEMO87id2MB+AeBB6NwGFgQuZgoE0PtgHIQhnmGuBFI8nAACZUcOmnUHRw6TtEkggA

**Comment by devanshj** [comment]
Great! Yep as I too said we'll keep this issue open till we publish a version with `createDefinition` exported.

Also needless to say right now you're using internals as a workaround, hence there's no guarantee that your code will not break with non-major bumps, so be careful. Once we export `createDefinition` migrate to that.

**Comment by smhmd** [comment]
Thanks both you guys for this issue. My use case involves React context (createContext) and TypeScript. What I had to do is the following:

```tsx
import { createContext, useContext } from 'react'

import useStateMachine from '@cassiozen/usestatemachine'
import { Machine } from '@cassiozen/usestatemachine/dist/types'

const MultiSelectContext = createContext<MachineType | null>(null) // initialize context

// define machine outside so I can have a type (see MachineType down below)
const machine = {
  initial: 'closed',
  states: {
    open: {
      on: {
        CLOSE: 'closed',
      },
    },
    closed: {
      on: {
        OPEN: 'open',
      },
    },
  },
} as const // as const because `useStateMachine` wouldn't work without it.

const Root = (props) => {
  const stateMachine = useStateMachine(machine)

  return (
    <MultiSelectContext.Provider value={stateMachine} {...props} />
  )
}

export const useMultiSelectMachine = () => {
  const ctx = useContext(MultiSelectContext)
  if (!ctx) {
    throw new Error('MultiSelect components must be wrapped with Root')
  }
  return ctx
}

type MachineType = [
  state: Machine.State<Machine.Definition.FromTypeParamter<typeof machine>>,
  send: Machine.Send<Machine.Definition.FromTypeParamter<typeof machine>>
]

```

It'd be great if future iterations cover this usage as well. (Unless there are better ways to consume same machine by multiple components -- XState seems to have `useInterpret` and `useActor`.)

(Note, the internal `Machine.Definition.FromTypeParamter` has a typo. It should be `FromTypeParameter`)

**Comment by devanshj** [comment]
Yeah that's problematic, #79 will solve this. And thanks for the feedback!

**Comment by KutnerUri** [comment]
@devanshj I think this is a great idea, maybe even just for perf - the configuration will be created once instead of every time the component is rendered. It is also possible that the createMachine function will include some optimizations in the future? though probably not.

In the meantime, all I want is de-cluttering, I guess I could just extract the hook to its own function
